name: bam-readcount-test
on: [push]
jobs:
  bam-readcount-build-and-ctest:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install lcov
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'
          architecture: 'x64'
      - run: mkdir build && (cd build && cmake -DCODE_COVERAGE=ON .. && make && make codecoverage)
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: 'build/codecoverage.info'
